cabaletta/baritone

src/main/java/baritone/api/event/GameEventHandler.java
```
for (IGameEventListener l : listeners) {
if (canDispatch(l)) {
l.onRenderPass(event);
}
}
```
average: 9153 nanoseconds
```
dispatch(listener -> listener.onRenderPass(event));
...
private void dispatch(Consumer<IGameEventListener> dispatchFunction) {
this.listeners.forEach(listener -> {
if (canDispatch(listener)) {
dispatchFunction.accept(listener);
}
});
}
```
average: 11541 nanoseconds
```
dispatch(listener -> listener.onRenderPass(event));
...
private void dispatch(Consumer<IGameEventListener> dispatchFunction) {
this.listeners.stream().filter(this::canDispatch).forEach(dispatchFunction);
}
```
average: 15262 nanoseconds
Tested over the first 30 seconds of frames rendered after loading a world, like so:
=> direct invocation

README.md, src/main/java/baritone/pathing/calc/AStarPathFinder.java, src/main/java/baritone/pathing/calc/MoveResult.java, src/main/java/baritone/pathing/calc/Moves.java, src/main/java/baritone/pathing/calc/Path.java, src/main/java/baritone/pathing/calc/PathNode.java, src/main/java/baritone/pathing/movement/MovementHelper.java, src/main/java/baritone/pathing/movement/movements/MovementAscend.java, src/main/java/baritone/pathing/movement/movements/MovementDescend.java, src/main/java/baritone/pathing/movement/movements/MovementDiagonal.java, src/main/java/baritone/pathing/movement/movements/MovementDownward.java, src/main/java/baritone/pathing/movement/movements/MovementFall.java, src/main/java/baritone/pathing/movement/movements/MovementPillar.java, src/main/java/baritone/pathing/movement/movements/MovementTraverse.java, src/main/java/baritone/utils/BlockStateInterface.java, src/main/java/baritone/utils/ExampleBaritoneControl.java, src/main/java/baritone/utils/pathing/BetterBlockPos.java
no more 50 million betterblockpos and betterblockpos[] for positionstobreak in cost calculation!!!
WIP
=> Gotta go fast, fixes #179, fixes #168

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/pathing/calc/IPathFinder.java, src/main/java/baritone/behavior/PathingBehavior.java, src/main/java/baritone/pathing/calc/AStarPathFinder.java, src/main/java/baritone/pathing/calc/AbstractNodeCostSearch.java
Unintentionally fixes #262 I have no idea why.
Anyway this adds a secondary cutoff. 
If you tell it to path, it will start executing after 500ms if it's found a path, but can continue calculating up to 2000ms if there is no valid (long enough) path found. Same goes for planning ahead, with 4000ms and 5000ms. This helps it get started as fast as possible, without compromising on its ability to find paths in really tricky situations that require lots of backtracking.
=> add a secondary failure cutoff

src/api/java/baritone/api/Settings.java, src/main/java/baritone/pathing/calc/AbstractNodeCostSearch.java, src/main/java/baritone/pathing/movement/CalculationContext.java, src/main/java/baritone/pathing/movement/Moves.java, src/main/java/baritone/pathing/movement/movements/MovementParkour.java
I made a promise to BluSpectrum in issue #650 that I would do what many (such as @0-x-2-2) thought to be impossible - allow Baritone to do upwards parkour jump to ascend
Since a parkour ascend and a parkour can never be possible in the same cardinal direction from the same origin, I opted to make the existing `MovementParkour dynamicY`. This purely adds new movement options, no previously valid `MovementParkour` is now invalid in favor of an ascend. As a part of this constraint, no ascend parkour place exists. This is because it's ambiguous if a parkour place or an ascend parkour place should be prioritized. For the same reason that parkour place only runs over a gap of 3, parkour place does not ascend.
BluSpectrum, I hope this helps you find happiness. 🤙
=> Add parkour ascend

src/api/java/baritone/api/utils/ExampleBaritoneControl.java
This fixes #782. Using #goto -100 -100 for example would send you to y=-100 rather than x=-100 z=-100. 
isNumeric returns false if the input is anything other than a positive integer. This meant that parseGoal wasn't correctly parsing goals that ended in 'impure' numbers (negatives, decimals, etc.). Replacing isNumeric with isCreatable fixes this
=> Stop parseGoal from removing the last argument (when it shouldn't)

src/api/java/baritone/api/Settings.java
Signs should also be avoided. A lot of history can get lost
Actually, before that gets merged, let me also add, hoppes along with other containers and restone things. Like restone itself and doors eg. maybe glass also?
=> added things to avoid

src/api/java/baritone/api/utils/command/datatypes/RelativeCoordinate.java
#1015 
This is my first pull request. This effectively converts a `#goto 1k 1k` to `#goto 1000 1000`
More work will be needed to convert 1.3k to 1300, as right now that should be an invalid argument.
=> #1015 Feature/1015/goal revamps

src/api/java/baritone/api/command/datatypes/RelativeGoal.java, src/api/java/baritone/api/command/exception/CommandErrorMessageException.java, src/api/java/baritone/api/command/exception/CommandException.java, src/api/java/baritone/api/command/exception/CommandInvalidArgumentException.java, src/api/java/baritone/api/command/exception/CommandInvalidTypeException.java, src/api/java/baritone/api/command/exception/CommandUnhandledException.java, src/main/java/baritone/command/argument/ArgConsumer.java, src/main/java/baritone/command/defaults/GotoCommand.java
When I run the `goto 0 0` command, it works but it prints this to stderr:
```
[14:58:17] [main/INFO]: [CHAT] [Baritone] > goto 0 0
[14:58:17] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandNotEnoughArgumentsException: Not enough arguments (expected at least 3)
[14:58:17] [main/INFO]: [STDERR]: 	at baritone.command.argument.ArgConsumer.requireMin(ArgConsumer.java:391)
[14:58:17] [main/INFO]: [STDERR]: 	at baritone.command.argument.ArgConsumer.get(ArgConsumer.java:262)
[14:58:17] [main/INFO]: [STDERR]: 	at baritone.command.argument.ArgConsumer.getString(ArgConsumer.java:270)
[14:58:17] [main/INFO]: [STDERR]: 	at baritone.api.command.datatypes.RelativeCoordinate.apply(RelativeCoordinate.java:37)
[14:58:17] [main/INFO]: [STDERR]: 	at …
```
=> Remove error message when running goto with less than 3 args

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/suggestion.md
Seriously pisses me off that somehow people don't know how markdown works. 
***
I've seen people use fucking emojis (#1282), `v`s (#1284), not even fill in the checkboxes in their issue or even have it like this once. 
```
- [ x] thng 1 
- [x ] Thing 2
- [ x] thing3
```
so the markdown doesn't work. 
This pull request would hopefully solve that so people learn to fill out issues properly.
***
An example of how this works when done properly (as shown by the templates):
=> Make how to use checkboxes more clear in issue templates 

src/api/java/baritone/api/Settings.java, src/main/java/baritone/pathing/calc/AbstractNodeCostSearch.java, src/main/java/baritone/utils/NotificationHelper.java
Solves #219 and #1269
Adds a desktop notification helper to Baritone, and sends a notification when a path is not found.
=> Desktop Notification System

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/BuilderProcess.java
Adds `startAtLayer<Int>` to start building the schematic at a specific layer. Can help on larger builds when schematic wants to break things its already built. 
You have very pretty feet.
=> Introduce startAtLayer 

src/api/java/baritone/api/utils/IPlayerContext.java
Removed an unused function that can't be used anyways, because RayTraceUtils cant detect entity hit...
=> 🔥 Get yeeted unused code

src/main/java/baritone/pathing/movement/movements/MovementDiagonal.java
This is the successor of #1922 and the result of the conversation there
it is a combination of 02e7886 and #1922 
Movement diagonal was considered to be always safe to cancel, but when cornering over air it isn't.
This caused baritone to reliably fall when backfilling at the source of a MovementDiagonal (Fixed #1788)
Added a check for a supporting block and only consider the current state safe when there is one that is canWalkOn
=> Fix MovementDiagonal being safeToCancel while cornering over air 2.0

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/process/IBaritoneProcess.java
fix 2 typos in java-doc.
fixes #1981
=> fix typo in java-doc x2

src/main/java/baritone/command/defaults/DefaultCommands.java, src/main/java/baritone/command/defaults/WaypointsCommand.java
It now is a combined `#wp goal` and `#path` just like `#goto` is `#goal` and `#path`
=> make `#wp goto` behave like `#wp goal` and `#path`

src/main/java/baritone/utils/GuiClick.java
When using the `#click` command the game would crash due to a NullPointerException.
This commit fixes that by not allowing a `null` value after clicking.
I am not sure about the chat message, but I think it's usefull to remind a player.
Maybe the chat message should be changed to a debug message?
=> Fixing crash after clicking into the air using the #click command

src/main/java/baritone/utils/IRenderer.java
In testing within Fabritone, it was found that these two lines (Which were previously used for an unknown optifine workaround) are no longer needed, and had no known side effects as of writing.
This can be backported as needed, but details are unknown how far this can go down
Future me PS: This PR is a superseed of my last one, erased during repo refactors, so now it lives on master branch. Testing recommended and can be up-ported/down-ported as you wish.
=> 🐛 Fix a Rendering Conflict with some other Mods

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/utils/Helper.java, src/api/java/baritone/api/utils/gui/BaritoneToast.java
This adds in a logAsToast and toastTimer option, and is a minified form of Indrit's initial implementation previously used from fabritone
=> ✨ Added Toast API Support

src/api/java/baritone/api/Settings.java, src/main/java/baritone/pathing/movement/MovementHelper.java, src/main/java/baritone/process/MineProcess.java
adds an exposed Ores only setting.
if there is air no air on any side then it removes it from the goal.
fixes #1168
=> add mineOnlyExposedOres setting

src/api/java/baritone/api/command/datatypes/EntityClassById.java
One of the Forge patches removes EntityList.REGISTRY and provides the getClass method as a replacement.
The fix is based on a similar one I found in WorldDownloader. See my comment in https://github.com/cabaletta/baritone/issues/1376#issuecomment-679300658
I tested that it now works fine both with and without Forge
Closes #1376 (and duplicates: #1777 and #1815)
=> Fix "#entity follow <name>" under Forge

build.gradle
this excludes the files making the jar a Forge mod unless the baritone.forge_build property exists.
This does effectively nothing on 1.12.2, as the files this change removes don't exist there
fixes #2124
=> don't make non-forge jars valid mods (fixes #2124)

SETUP.md
This will save someone some time figuring out why there are no forge jars
=> Add instructions to build with forge for minecraft 1.15+

build.gradle
SpongePowered recently changed their Maven repo URL, so this is the right one
=> Fix SpongePowered Maven repo URL

src/launch/java/baritone/launch/mixins/MixinSodiumChunkProvider.java, src/launch/java/baritone/launch/mixins/MixinSodiumFixedLongHashTable.java, src/launch/resources/mixins.baritone.json, src/main/java/baritone/utils/accessor/ISodiumChunkArray.java
This addition adds compatibility for https://github.com/jellysquid3/sodium-fabric to baritone. It is done in this way with `@Pseudo` in order for the non fabric builds to not have issues since they obviously wouldn't be able to reference a fabric mod. this is a follow up to #2086
=> compatibility for SodiumChunkManager

src/api/java/baritone/api/Settings.java, src/main/java/baritone/behavior/InventoryBehavior.java, src/main/java/baritone/utils/ToolSet.java
stops baritone using a item when it gets down to 1 durability.
fixes #997
closes #1354
=> add itemSaver setting.

src/main/java/baritone/cache/ChunkPacker.java
Hi there!! This is more of a discussion PR, because not sure if this is intended or not.
But anyways, I was working with the baritone API and I kept seeing this error being spammed in console from this chunk of code:
```[baritone.cache.ChunkPacker:pack:84]: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
[baritone.cache.ChunkPacker:pack:84]: 	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:137)
[baritone.cache.ChunkPacker:pack:84]: 	at net.minecraft.block.BlockLiquid.getFlowVector(BlockLiquid.java:185)
[baritone.cache.ChunkPacker:pack:84]: 	at …
```
=> Fixed incorrect block pos world coordinates

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/schematic/CompositeSchematic.java, src/api/java/baritone/api/schematic/ISchematic.java, src/api/java/baritone/api/schematic/ReplaceSchematic.java, src/main/java/baritone/process/BuilderProcess.java
Some of Baritone's schematics have a cache, that becomes outdated when the schematic is moved by `buildRepeat`. For expamle this caused `#replace` combined with `#buildRepeat` to always replace the same positions relative to the origin of the schematic.
Since this behaviour is actually being used, I added a setting to toggle it and set the default to not change anything.
fixes #1925
=> Clear caches of schematics when moving them

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/schematic/FillSchematic.java, src/api/java/baritone/api/schematic/SubstituteSchematic.java, src/api/java/baritone/api/utils/SettingsUtil.java, src/main/java/baritone/process/BuilderProcess.java
This adds the following new settings
* `#buildSkipBlocks` a list of blocks that are treated as if they were outside the schematic
* `#buildValidSubstitutes` a mapping of blocks to blocks that are treated as correct in their position<br>the same as what `#buildIgnoreExisting` does, but more general
* `#buildSubstitutes` a mapping of blocks to blocks that will be placed instead, preferring blocks in the order they are given in
While writing this I noticed that this additionally "breaks" buildIgnoreBlocks so that the behaviour is now the same for filling and building schematics from disk and fits the behaviour the user would expect after reading the documentation, which wasn't the case for filling.
closes #2323
closes #2225
fixes #2344 
fixes #2318
and from what @scorbett123 said I conclude …
=> Settings to alter block treatment while builing

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/BuilderProcess.java, src/main/java/baritone/utils/schematic/SelectionSchematic.java
I have made it like it was suggested in #2612, but I'm not really happy with it because
* I think it should be useable for `#build` as well (easy with the current implementation, just have to copy the logic to the respective method)
* I don't like the fact that it is a setting functioning as an argument (`#schematica <selectionOnly` but what signature would `#build` have?)
and less important
* I don't like the fact that it is a schematic knowing it's own (initial) position, but can't think of a cleaner solution
* a better name would be nice
closes #2612
=> Add setting to only build selected part of schematica schematic

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/command/helpers/TabCompleteHelper.java, src/api/java/baritone/api/utils/Helper.java, src/api/java/baritone/api/utils/NotificationHelper.java, src/api/java/baritone/api/utils/SettingsUtil.java, src/api/java/baritone/api/utils/gui/BaritoneToast.java, src/main/java/baritone/command/ExampleBaritoneControl.java, src/main/java/baritone/command/defaults/SetCommand.java, src/main/java/baritone/pathing/calc/AbstractNodeCostSearch.java, src/main/java/baritone/process/BuilderProcess.java, src/main/java/baritone/process/CustomGoalProcess.java, src/main/java/baritone/process/ExploreProcess.java, src/main/java/baritone/process/FarmProcess.java, src/main/java/baritone/process/MineProcess.java
This makes the notification function a setting called `notifier` just like logging to chat uses `logger` and because I accidentally did it for toasts instead of notifications at first (don't trust the commit history), toast now have a setting called `toaster` (but it can't roast bread :disappointed:).
This makes it possible for external mods to implement #2598.
Additionally I replaced the unhandled excpetion when accessing these settings with commands with a more descriptive error message, to avoid issues like #1593
=> More log callbacks

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/MineProcess.java
Previously, `MineProcess` explored depending on `legitMine`
It currently uses `legitMineYLevel` like before for `legitMine`, but there is also `exploreMaintainY` (used by `ExploreProcess`) or nothing (`GetToBlockProcess`) and I wonder if I should change exploring for ores without legit mode to use one of the alternatives. 
closes #2733
fixes #1637
fixes  #1017
fixes #766
=> Make MineProcess respect exploreForBlocks

README.md
Remove this broken badge. I haven't seen it working at all in the past few weeks.
=> Remove broken hit count badge

src/api/java/baritone/api/Settings.java, src/main/java/baritone/behavior/InventoryBehavior.java, src/main/java/baritone/utils/ToolSet.java
This setting allows you to change the durability at which baritone should stop using a tool when using the itemSaver setting. Currently baritone will stop using the tool when it's at 0 durability which sometimes breaks it. I've set the default value to 10 to give a little buffer to avoid tools breaking.
=> Added itemSaverThreshold setting

src/main/java/baritone/command/defaults/SelCommand.java
Behaviour should be the same as WorldEdit `//copy` and `//paste` but with the possibility to explicitly specify the reference position
closes #1785
=> ✨ Add a clipboard to #sel

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/BuilderProcess.java
Because it hurts watching it clear 1 block layers of a 257x257x257 sphere.
There's a rough alternative implementation at https://github.com/ZacSharp/baritone/tree/layerHeight2, which has the benefit of not changing the layer associated with a certain height in blocks, making it more usable when changing `layerHeight` halfway through a build.
closes #1756
=> ✨ Add layerHeight setting

scripts/proguard.pro
Currently every build is failing as soon as it is run.
This seems to be to do with a update in one of the dependencies changing the version of patchy, which wasn't later changed in proguard.pro leading to a null pointer exception.
=> Fix proguard from being broken.

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/BuilderProcess.java
Toggling this option will let baritone place glazed terracotta, bone blocks and hay bales freely.
Current behavior (with buildignoreexisting false) often includes continuous breaking and placing the same block, as baritone does not understand how to place a block so it faces the right way.
=> Option to ignore direction of certain blocks during building

src/main/java/baritone/pathing/movement/MovementHelper.java
player can get stuck on the "irregular" blocks if looking at the center of the block doesn't actually target it for breaking. I see that as "acceptable" but lmk if I should dynamically add them to blocksToAvoidBreaking as they come up
fixes #2148
=> fix Null params on getCollisionShape causing NPEs

build.gradle
there was an issue where one of the eclipse org dependencies updated to require java 11 on a minor version, changing to loom 7 fixes it... please consider merging #2814 instead of going up with this to 1.16
=> Fix fabric building due to dependency issue

src/main/java/baritone/cache/WorldProvider.java
On some newer versions of minecraft replaymod will leave some fields null causing a NPE when loading/viewing a replay. Since you can't baritone in replays anyway, I just cancel the function and set the current world to null. 
realms is false so when merging up you can have that as it's own if statement outside this one. ie,
```java
String folderName;
if (mc.isConnectedToRealms()) {
folderName = "realms";
} else {
if (mc.getCurrentServerData() != null) {
folderName = mc.getCurrentServerData().serverIP;
} else {
//replaymod causes null currentServerData and false singleplayer.
currentWorld = null;
return;
}
}
```
https://github.com/wagyourtail/baritone/tree/replaymod-1.16.5
fixes #2619, #2769 (more detailed duplicate)
=> fix replaymod crash (on newer versions)

src/api/java/baritone/api/pathing/movement/ActionCosts.java, src/test/java/baritone/pathing/movement/ActionCostsTest.java
```java
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 257 out of bounds for length 257
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: 	at baritone.pathing.movement.movements.MovementDescend.dynamicFallCost(MovementDescend.java:146)
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: 	at baritone.pathing.movement.movements.MovementDescend.cost(MovementDescend.java:104)
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: 	at baritone.pathing.movement.Moves$11.apply(Moves.java:165)
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: 	at baritone.pathing.calc.AStarPathFinder.calculate0(AStarPathFinder.java:118)
[01:26:37] [pool-3-thread-3/INFO]: [STDERR]: 	at baritone.pathing.calc.AbstractNodeCostSearch.calculate(AbstractNodeCostSearch.java:104)
[01:26:37] …
```
=> fix an array oob with dynamic worldheight

src/main/java/baritone/pathing/movement/CalculationContext.java, src/main/java/baritone/pathing/movement/MovementHelper.java, src/main/java/baritone/utils/BlockStateInterface.java
Add world border checks to where they weren't previously, will help in a few cases. 
World border checks where already implemented in the actual A* though, so no edits have been done to that area of pathfinding.
Closes #3236
=> Add some world border checks

scripts/proguard.pro
I could not use `@KeepName` because it is in the main source set.
Fixes #3089
=> Fix chat error messages being obfuscated for block type arguments

src/launch/java/baritone/launch/mixins/MixinItemTool.java, src/launch/resources/mixins.baritone.json, src/main/java/baritone/utils/ToolSet.java, src/main/java/baritone/utils/accessor/IItemTool.java
as per @ZacSharp 's comment in [#3008](https://github.com/cabaletta/baritone/issues/3008#issuecomment-1024290682), use harvistability level.
(I tested with cofh and it appears to have fixed that)
gold and wood have the same harvest level, but I don't think it really matters if the bot chooses the "wrong" (rarer) one between those two...
fixes #3008
=> fix modded toolmaterials (1.12.2)

gradle/wrapper/gradle-wrapper.properties, src/main/java/baritone/pathing/movement/MovementHelper.java, src/main/java/baritone/process/BuilderProcess.java
mojang decided getStateForPlacement can return null if placing against a block wouldn't work.
should I just use defaultBlockState instead?
builder2 will fix this anyway if leij makes it work with blockstates...
this also happens on 1.16.5 probably. (I'm betting #3103 is this)
fixes #3298, #3165, #3106, #3244, #3205, #3102 
there's probably at least one more....
the development tab on the left doesn't show them for some reason... so they won't auto-close.
a easy reproduce of the bug this is fixing: enable allow inventory and stand on path block with a button in your inventory. then do `#sel fill dirt`
=> fix `<parameter1> is null`

src/main/java/baritone/cache/CachedWorld.java
This fixes a really rare error which will crash the region saving thread, thus making it not save regions when they are explored.
This crash of that thread only occurs when time loading the minecraft world is > 30 seconds, making it pretty rare, however in these cases IPlayerContext.player() returns null, so we need to protect against this in guessing the position.
closes #3289
=> If context.player() returns none we don't want to use its position for pruning.

src/main/java/baritone/command/defaults/MineCommand.java
Baritone no longer caches ores on Minecraft 1.13+
Metadata values were removed in Minecraft 1.13
lit_redstone_ore was merged into redstone_ore in Minecraft 1.13
=> Remove false information from `#help mine`

buildSrc/src/main/java/baritone/gradle/task/BaritoneGradleTask.java, settings.gradle
Alright the rootProject name is present on all branches from master to 1.16 and is missing on 1.17 and higher, so I'm adding it back to 1.17
=> Build fix 1.17

scripts/proguard.pro
this fixes Setting.value issue in ide's when using the api jar as a dependency
why didn't I do this sooner. I've known about this issue for like a year...
=> fix inner class attribute being stripped

build.gradle
Newer Mixin versions use a class file format Proguard can't handle.
This is an alternative to #3371 and since it avoids problems with further updates I would personally prefer merging this one and closing the other.
=> Fix dynamic mixin dependency to 0.8.3

src/main/java/baritone/command/defaults/ETACommand.java
Currently it outputs in ticks, however it is easier to understand when there is also a second estimate.
=> Improve output to user in eta command

src/main/java/baritone/process/BuilderProcess.java
This caused positions outside the schematic being marked as incorrect (because they were incorrect in the previous build) and if those positions are queried to determine the needed material the result is `null`, leading to the error message that you are missing items to place null.
Fixes #3428
Fixes #2720
Closes #3432
Also there are a few older issues that are possibly for this bug as well but they used Baritone versions that don't list the missing materials so I can't tell from the logs.
=> Fix "missing null"

src/main/java/baritone/pathing/path/PathExecutor.java
In the case where we're descending stairs and need to stop at the bottom to mine a block to our left or right. If the next space is lava or a hole, we'll currently overshoot right into it even with default settings.
Currently 
```
if (next instanceof MovementDescend && next.getDirection().equals(current.getDirection())) {
return true;
}
```
is checked first inside the canSprintFromDescendInto, which will return True before MovementHelper.canWalkOn is checked. 
Checking MovementHelper.canWalkOn first ensures we won't sprint onto a block where the next block is not walkable.
=> Fix for a sprint bug that can cause death

src/main/java/baritone/pathing/movement/MovementHelper.java
Only affects `allowOnlyExposedOres` because nothing else uses that method.
Fixes #3637
=> Fix yet another cave air bug

src/api/java/baritone/api/Settings.java
Update the legit mine default setting to work at the correct diamond level in 1.18+.
=> Update legitMineYLevel for 1.18 +

src/main/java/baritone/process/BackfillProcess.java
It's not perfect; while paused, it will still attempt to fill in any blocks that were added to blocksToReplace while running. So for example, if you pause it, then break a block that was previously backfilled, it will instantly replace it. For any other block however, it will not fill it.
=> Stop backfill from filling while paused

src/main/java/baritone/pathing/movement/Movement.java, src/main/java/baritone/pathing/movement/movements/MovementTraverse.java
This is a slightly dodgy solution, however it is the simplest one I could think of.
When a fall into more than 2 block deep water occurs baritone enters an infinite loop as we swim up, to the surface, and end the movement when we "jump" above the water, this means that our position isn't in the valid positions of a traverse movement. And thus some of the lag protection jumps in and resets us to the fall (as this is a valid position for during the fall), entering an infinite loop.
Closes #3200.
If anyone can think of a better solution to this please let me know
=> Fix for infinite loop in water

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/BuilderProcess.java
Specifying property names per block might also be desired, should I change it to be per block?
Fixes #3696
Fixes #3610 (probably the same as #3696)
Closes #2854
=> ✨ Add buildIgnoreProperties setting

src/main/java/baritone/process/MineProcess.java
even if it will cause issues with ores beyond walls...
idk if that's fixable, theoretically the allowbreaklist could have something common like stone on it so we can't just check if it's surrounded by not air
but I still think this change is worth making
=> allowBreakAnyway should let mining happen

buildSrc/src/main/java/baritone/gradle/task/ProguardTask.java
Most of my development happens in numbered directories, so I ended up with a bunch of `D:\01 - Repositories\Baritone\...` everywhere. Proguard does not like that.
I also tried the windows escape thing, which is prefixing spaces by `^`, that didn't work either, in case you were wondering.
Tested on 1.2.15
=> Improve handling spaces in paths during proguard pass

src/api/java/baritone/api/command/datatypes/RelativeCoordinate.java
The commit is anything but special, and i dont know if the owners intended the way it was before as its a really simple "fix"
Basically it enables the use of different decimal units abreviations other than just the lowercase k in this case it allows K, m and M(the m is for million)
_If you are wondering why would i make this, i use impact and apparently on the version im using .goto -xk y zk apparently does not work, due to me using baritone directly and impact interchangibly i started to think it was a baritone issue but apparently it isnt any way i might as well add something to it_
=> Added the ability to use KmM as abreviatures

src/main/java/baritone/cache/WorldProvider.java
This checks whether `mc.world` changed on every access to the cached world.
Includes the check wagyourtail applied on 1.19.3 just in case.
closes #3031
closes #3603
closes #3141
=> Make the world cache work even when mods break our world load hook

src/api/java/baritone/api/utils/BlockOptionalMeta.java, src/api/java/baritone/api/utils/BlockOptionalMetaLookup.java, src/launch/java/baritone/launch/mixins/MixinBitArray.java, src/launch/java/baritone/launch/mixins/MixinBlockStateContainer.java, src/main/java/baritone/BaritoneProvider.java, src/main/java/baritone/cache/FasterWorldScanner.java, src/main/java/baritone/command/defaults/MineCommand.java, src/main/java/baritone/command/defaults/PathCommand.java, src/main/java/baritone/command/defaults/RepackCommand.java, src/main/java/baritone/process/FarmProcess.java, src/main/java/baritone/process/MineProcess.java, src/main/java/baritone/utils/accessor/IBitArray.java, src/main/java/baritone/utils/accessor/IBlockStateContainer.java
to confirm my results, change `getWorldScanner` back in `BaritoneProvider`.
use max render distance on single player (32 chunks)
thank you @Etheradon for the parts of the code I "borrowed" from the jsmacros implementation. which I now realize after having tested it in baritone, the 1.12 version is wrong... so I guess I'll have to fix that as well...
the real trick is that I'm cheating with parallelStream, caching block states for faster lookup, and (probably the biggest one) checking the subsection's pallete directly to see if it even exists instead of iterating over the contents
=> replace the world scanner with a 500x faster one

src/api/java/baritone/api/Settings.java, src/main/java/baritone/process/MineProcess.java
Behavior on 1.12.2 is obvious, but I'm not sure what to do when updating.
The option I prefer is simply bumping the default value to be the maximum maximum build height (Baritone doesn't work in CubicChunks worlds, right?), but for consistency with `minYLevelWhileMining` we'd need to also offset it by the minimum build height.
@wagyourtail why is `minYLevelWhileMining` offset by the minimum y anyway? Just so the default can stay at 0 or is there another reason?
closes #1883
=> ✨ Add maxYLevelWhileMining setting

src/api/java/baritone/api/utils/BlockOptionalMeta.java
Examples:
*  `#mine log[variant=oak]`
*  `#sel fill log[axis=y]` (if you build on a flat surface it won't even fail) 
*  `#sel replace wheat[age=7] air`
* `#goto chest[facing=north]`
Basically you can now specify any blockstate and it will ignore any property you didn't specify.
The only "breaking api change" is that the return value of `getMeta` is even less useful now, but I don't see a problem in that so here we go.
closes #1760 (even though the author said "nbt" instead of "block properties")
=> Extend BlockOptionalMeta parsing to parse block properties

src/api/java/baritone/api/Settings.java, src/api/java/baritone/api/command/helpers/TabCompleteHelper.java, src/api/java/baritone/api/utils/SettingsUtil.java, src/main/java/baritone/command/ExampleBaritoneControl.java, src/main/java/baritone/command/defaults/SetCommand.java
Replaces the `JAVA_ONLY_SETTINGS` array with a `@JavaOnly` annotation on the fields themselves.
I don't think there's anything else that should be addressed with annotations atm so this PR should be good to go.
=> Setting Field Metadata

src/main/java/baritone/command/defaults/SelCommand.java, src/main/java/baritone/selection/SelectionRenderer.java, src/main/java/baritone/utils/IRenderer.java, src/main/java/baritone/utils/PathRenderer.java
Reduces the number of `draw()` calls every frame from upwards of a few hundred to <10
I'm thinking about creating a separate `GoalRenderer` API though so that batching can be done a little smarter, especially with `GoalComposite`. (Would also help with cleaning up the current `drawGoal` mess)
=> Batch Rendering

src/main/java/baritone/utils/PathRenderer.java
Minecraft version 1.18 introduced a change to the game's world height.
Baritone uses hardcoded values for minY and maxY when rendering the GoalXZ box, even in the newer game versions.
This pull request uses the minimum and maximum build height from the player's current level.
Before:
After:
=> Add proper level height to GoalXZ rendering (1.18+)

src/api/java/baritone/api/schematic/mask/shape/CylinderMask.java
This took far too much time to find.
The problem was that `getA` and `getB` used the `alignment` field to determine their return value, but when calculating `centerA` and `centerB` based on `getA` and `getB` in the constructor `alignment` is still null.
I could have just moved the initialization of `this.alignment` to the top of the constructor, but this way there is no calls to instance methods in the constructor at all and no risk of accidentally messing it up again.
=> Fix `CylinderMask` with horizontal alignment

src/main/java/baritone/command/defaults/SetCommand.java
Error messages could also be improved. Specifically "Not a file" and "Not readable" shouldn't lead to generic "An exception occurred" messages.
=> Tab complete the file argument for `#settings load`

src/api/java/baritone/api/utils/BlockOptionalMetaLookup.java
@wagyourtail is there any specific reason why they weren't used?
=> Actually use stack hashes

src/api/java/baritone/api/command/datatypes/BlockById.java, src/api/java/baritone/api/command/datatypes/ForBlockOptionalMeta.java, src/main/java/baritone/command/argument/ArgConsumer.java, src/main/java/baritone/command/defaults/GotoCommand.java, src/main/java/baritone/command/defaults/MineCommand.java, src/main/java/baritone/command/manager/CommandManager.java
I noticed that on 1.13+ while typing a block with properties (e.g. `lever[powered=false]`) it was printing an exception for every single character I typed, because mc didn't like `BlockById.tabComplete` trying to construct a `ResourceLocation` with "[" or other non [a-z0-9._-] characters.
Originally I intended to fix this by completely rewriting the tab completion, but as you can see in the second commit that plan had a flaw so I had to do the fix separately.
Also comes with some minor improvements like tab completion for `#mine` working beyond the first argument and `#goto` not completing more arguments than it accepts.
=> Tab completion improvements

src/api/java/baritone/api/schematic/mask/operator/BinaryOperatorMask.java
It still doesn't check `x >= 0 && y >= 0 && z >= 0` because caller has to check that anyway.
Also changes `BinaryOperatorMask` to be as big as the bigger of the two component masks.
=> Don't call `partOfMask` out of bounds in `BinaryOperatorMask`

buildSrc/src/main/java/baritone/gradle/task/ProguardTask.java
because I can configure the gradle runtime for baritone in intellij
=> proguard: get java from gradle runtime before JAVA_HOME
