- buildSrc/src/main/java/baritone/gradle/util/Determinizer.java
Determinizer description was incorrect.
> Fixed serious issue.

- src/api/java/baritone/api/utils/SettingsUtil.java
scanner is an outdated artifact of the 20th century.
> real gamers use bufferedreader

- .travis.yml
> use runAutoTest

- src/api/java/baritone/api/Settings.java
- src/api/java/baritone/api/utils/SettingsUtil.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/utils/pathing/Avoidance.java
> [Change] Add Block Avoidance Settings

- .gitattributes
> Automatic CRLF -> LF normalization

- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
> Added the command delete. Allows you to remove a user defined waypoint.

- src/main/java/baritone/process/FollowProcess.java
> daily commit

- README.md
> Speed up production

- src/main/java/baritone/utils/pathing/Avoidance.java
Third time's a charm.
uwu sorry
> Added Spider, PigZombie and Enderman conditions

- src/main/java/baritone/process/FarmProcess.java
PICKUP_DROPPED:
Remove 2nd Items.WHEAT
Re-order a few items for neatness
Edit for clarity: Remove duplicate Items.WHEAT
> PICKUP_DROPPED - Remove 2nd Items.WHEAT

- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
This was all basically control c, control v but aight.
Requested in #552
> FollowEntity and FollowEntities

- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
im sorry ~~uwu~~ it wont happen again.
@ZeroMemes sowwy
> I forgot players and items were entities too

- USAGE.md
- build.gradle
- scripts/proguard.pro
- src/api/java/baritone/api/process/IBuilderProcess.java
- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/utils/schematic/schematica/SchematicAdapter.java
- src/main/java/baritone/utils/schematic/schematica/SchematicaHelper.java
- src/schematica_api/java/com/github/lunatrius/core/util/math/MBlockPos.java
- src/schematica_api/java/com/github/lunatrius/schematica/Schematica.java
- src/schematica_api/java/com/github/lunatrius/schematica/api/ISchematic.java
- src/schematica_api/java/com/github/lunatrius/schematica/client/world/SchematicWorld.java
- src/schematica_api/java/com/github/lunatrius/schematica/proxy/ClientProxy.java
- src/schematica_api/java/com/github/lunatrius/schematica/proxy/CommonProxy.java
> build the schematic schematica has open

- src/main/java/baritone/utils/PathRenderer.java
> Disable lighting on path renderer

- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
Its an option to add a dimension and it will convert to coords (if you are in overworld and add nether it will multiply the coords by 8 eg). I made it as short as possible.
features:
-only multiplies x and z values
-works for end, overworld and nether
because it doesnt make -doesnt multiply if ~ is inputed
-you dont have to input it but if you want just add it to the end of the goal or goto command
> dimensional coords extension

- src/api/java/baritone/api/Settings.java
> Just a little fix, you know was coding away and thought, "hey! here is something cool!"

- USAGE.md
I didn't know you could do this, but you can.
> Added amount of block mining to documentation

- src/api/java/baritone/api/Settings.java
- src/api/java/baritone/api/utils/SettingsUtil.java
- src/main/java/baritone/behavior/InventoryBehavior.java
> Replace klass with cla$$

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/process/FarmProcess.java
add replantCrops setting, simmilar to replantNetherWart for the other crops.
Usefull to disable when f.E. raiding villiges
> Add replantCrops setting

- src/api/java/baritone/api/utils/ExampleBaritoneControl.java
before, saving a waypint with a tag name would not result in an error, but you would not be able to run "goto" on it. see #869
> Check if waypoint name is Tag

- src/api/java/baritone/api/utils/command/Command.java
- src/main/java/baritone/utils/command/defaults/ComeCommand.java
- src/main/java/baritone/utils/command/defaults/ExploreFilterCommand.java
- src/main/java/baritone/utils/command/defaults/RenderCommand.java
Why would he do this when mc field exists.
> Remove retarded MC field.

- src/main/java/baritone/cache/ChunkPacker.java
> Fix a MAJOR bug caused by the JetBrains™ AutoFormatter™

- CODE_OF_CONDUCT.md
added additional details to standards
-line 20
-line 17
-line 32
> Updated Standards section of CODE_OF_CONDUCT.md

- src/api/java/baritone/api/Settings.java
- src/api/java/baritone/api/utils/BlockUtils.java
- src/api/java/baritone/api/utils/command/BaritoneChatControl.java
- src/api/java/baritone/api/utils/command/argparser/DefaultArgParsers.java
- src/api/java/baritone/api/utils/command/datatypes/ForWaypoints.java
- src/api/java/baritone/api/utils/command/datatypes/RelativeFile.java
- src/main/java/baritone/process/MineProcess.java
- src/main/java/baritone/utils/command/defaults/EmptyCommand.java
- src/main/java/baritone/utils/command/defaults/ExploreFilterCommand.java
- src/main/java/baritone/utils/command/defaults/SelCommand.java
- src/main/java/baritone/utils/command/defaults/WaypointsCommand.java
> Removed very angry code. Started feeding Codacy.

- src/api/java/baritone/api/event/listener/IGameEventListener.java
- src/api/java/baritone/api/utils/command/argparser/ArgParserManager.java
- src/api/java/baritone/api/utils/command/argument/CommandArgument.java
- src/api/java/baritone/api/utils/command/datatypes/ForWaypoints.java
- src/api/java/baritone/api/utils/command/helpers/arguments/ArgConsumer.java
> Attempt to "fix" travis.

- CODE_OF_CONDUCT.md
> Merge master into commands.

- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/pathing/movement/movements/MovementParkour.java
- src/main/java/baritone/pathing/path/PathExecutor.java
- src/main/java/baritone/utils/BlockStateInterface.java
- src/main/java/baritone/utils/BlockStateInterfaceAccessWrapper.java
> Fix isPassable crash

- .github/ISSUE_TEMPLATE/bug.md
> Add Linux support to issue templates

- SETUP.md
> Make setup instructions more clear

- src/main/java/baritone/command/defaults/TunnelCommand.java
Remake of https://github.com/cabaletta/baritone/pull/740 for the new command system.
Solves #319, #474, and [this impact issue](https://github.com/ImpactDevelopment/ImpactIssues/issues/1997).
> #740 (Custom tunneling) Updated for new command system

- USAGE.md
> Update USAGE.md as per #1332

- .github/ISSUE_TEMPLATE/bug.md
> Add modified settings to bug template

- USAGE.md
> Fix broken API Settings link in USAGE. Close #1040

- src/main/java/baritone/BaritoneProvider.java
- src/main/java/baritone/command/ExampleBaritoneControl.java
> bring back ExampleBaritoneControl

- src/api/java/baritone/api/utils/BlockOptionalMeta.java
> Fix #mine in forge

- README.md
uwu very important readme update :3
> Added blue badge to integrations badges

- README.md
HUGE CHANGES!!!!
updated the compatible versions to the future integrations badge
> updated compatible versions to future badge

- build.gradle
- src/api/java/baritone/api/command/helpers/Paginator.java
- src/api/java/baritone/api/utils/Helper.java
- src/api/java/baritone/api/utils/IPlayerContext.java
- src/launch/java/baritone/launch/mixins/MixinMinecraft.java
- src/launch/java/baritone/launch/mixins/MixinScreen.java
- src/main/java/baritone/cache/WorldProvider.java
- src/main/java/baritone/command/BaritoneChatControl.java
- src/main/java/baritone/command/defaults/ChestsCommand.java
- src/main/java/baritone/command/defaults/ComeCommand.java
- src/main/java/baritone/command/defaults/HelpCommand.java
- src/main/java/baritone/command/defaults/SetCommand.java
- src/main/java/baritone/command/defaults/WaypointsCommand.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/utils/GuiClick.java
- src/main/java/baritone/utils/ToolSet.java
Simplified the Port with #1889 related data and some code cleaning
> [Change] Updated Mappings + Simplified Port

- src/launch/java/baritone/launch/mixins/MixinMinecraft.java
- src/main/java/baritone/utils/BaritoneAutoTest.java
> [Fix] Fixed BaritoneAutoTest in 1.16.1

- README.md
as of rusherhack v1.0 there is baritone API integration, similar to future's.
> add rusherhack integration badge

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/utils/ToolSet.java
> Add auto tool setting

- src/main/java/baritone/command/defaults/GotoCommand.java
> Fixed Typo

- scripts/proguard.pro
- src/main/java/baritone/KeepName.java
- src/main/java/baritone/command/defaults/FollowCommand.java
> Annotation for proguard -keep

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/process/CustomGoalProcess.java
- src/main/java/baritone/process/ExploreProcess.java
- src/main/java/baritone/process/FarmProcess.java
- src/main/java/baritone/process/MineProcess.java
Closes https://github.com/cabaletta/baritone/issues/1345
> Make desktop notifications more useful

- src/main/java/baritone/Baritone.java
- src/main/java/baritone/utils/BaritoneProcessHelper.java
> Don't call onLostControl on processes that haven't been fully constructed

- src/main/java/baritone/command/defaults/DefaultCommands.java
- src/main/java/baritone/command/defaults/SurfaceCommand.java
> ✨ Added a top/surface command

- SETUP.md
added necessary commands and download links
> added jdk 8 instructions for macOS in SETUP.md

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/process/MineProcess.java
adds a minimum Y level while mining.
fixes #1883.
> add a minimum Y level during mining.

- README.md
rootNET supports the latest version of Baritone, this change reflects that
> Update rootNET's supported version

- USAGE.md
> Correct usage for mining a specific amount

- src/main/java/baritone/process/BuilderProcess.java
at least partially implements #2180 and closes it if there are no other reasons for "Unable to do it" being reported
> Log blocks the builder can't place (missing or obstructed by flowing liquid) when failing

- src/api/java/baritone/api/process/IFarmProcess.java
- src/main/java/baritone/command/defaults/FarmCommand.java
- src/main/java/baritone/process/FarmProcess.java
farm - farms every crop it can find.
farm 100 - farm crops within a 100 block radius from the starting position.
> Added range argument to farm

- src/main/java/baritone/behavior/MemoryBehavior.java
> notify users that their death position has been saved.

- src/main/java/baritone/process/BuilderProcess.java
> Don't crash by buildRepeating too often

- src/api/java/baritone/api/behavior/IPathingBehavior.java
- src/api/java/baritone/api/pathing/goals/Goal.java
- src/api/java/baritone/api/pathing/goals/GoalComposite.java
- src/api/java/baritone/api/pathing/goals/GoalInverted.java
- src/api/java/baritone/api/pathing/goals/GoalNear.java
- src/api/java/baritone/api/pathing/goals/GoalRunAway.java
- src/api/java/baritone/api/pathing/goals/GoalStrictDirection.java
- src/main/java/baritone/behavior/PathingBehavior.java
- src/main/java/baritone/command/defaults/DefaultCommands.java
- src/main/java/baritone/command/defaults/ETACommand.java
- src/main/java/baritone/command/defaults/EtaCommand.java
- src/main/java/baritone/process/GetToBlockProcess.java
- src/main/java/baritone/process/MineProcess.java
Closes #16 (full-path eta)
Closes #1480 (`#eta`)
> ✨ Add improved ETA and a command to access it

- src/main/java/baritone/command/defaults/SetCommand.java
This will help massively.
Biggest change since the initial commit.
> Improve #modified command to include original setting value.

- README.md
Hopefully I didn't mess with the blame at the bottom this time
-center the badges
-re-arrange them to be more organized
-update the Aristois/Impact badges to the correct versions and fix broken link
> Center badges and other stuff

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/utils/ToolSet.java
> Invert disableAutoTool to autoTool

- USAGE.md
Added missing information about the `farm` command.
> Added missing information to USAGE.md

- .github/ISSUE_TEMPLATE/bug.md
Otherwise people don't seem to fill it in, they probably won't still, however it may make more do so.
> switch from forge mods to just other mods.

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/utils/PathRenderer.java
Does what it says, if this setting is set to true it'll disable the animations on the goals. 
Closes #2171
> Add "RenderGoalAsBox" Setting

- src/main/java/baritone/behavior/InventoryBehavior.java
Allow #farm to retrieve items from your inventory.
> Make farm use inventory when allowInventory is enabled.

- .gitignore
- src/main/java/baritone/pathing/movement/movements/MovementParkour.java
Allows parkour place to consider 2 and 1 block jumps
Fixes #2350
> ParkourPlace for shorter parkour jumps

- README.md
> LEIJURV STOP BEING LAZY

- src/main/java/baritone/process/GetToBlockProcess.java
> Make rightClickContainerOnArrival click lit furnaces

- README.md
- src/main/java/baritone/process/BuilderProcess.java
zac suggested doing this more broadly on the previous pull request
> Better buildignoredirection

- src/main/java/baritone/command/defaults/ExecutionControlCommands.java
Some people can't seem to find out what to do to unpause baritone, so this should hopefully help them figure it out, as for some reason unpause makes more sense to people than resume.
> Add unpause as an alias for resume

- build.gradle
- src/main/java/baritone/pathing/movement/MovementHelper.java
> fix dripleaf and azalea behavior

- src/main/java/baritone/pathing/movement/MovementHelper.java
> fix getting stuck in powdered snow

- src/main/java/baritone/pathing/movement/MovementHelper.java
> fix getting stuck on cauldrons (fixes #3099)

- src/main/java/baritone/utils/BlockStateInterface.java
use world not worldData to prevent npe when in replaymod replay
oopsie while merging up
> replaymod replay crash fix 1.17+ 

- README.md
- SETUP.md
- USAGE.md
- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/command/defaults/FindCommand.java
Also fix 2 settings that just don't have a description for some reason, and add some information to the find command because that also for some reason did not have anything there. The descriptions I put may not be detailed enough so please let me know if things should change
> Update Setup and Usage guides

- src/main/java/baritone/pathing/movement/MovementHelper.java
> fix amethyst bud stuck 

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/Baritone.java
- src/main/java/baritone/behavior/WaypointBehavior.java
> reimplement death and bed waypoints

- src/launch/java/baritone/launch/mixins/MixinClientPlayNetHandler.java
> move death event to work with `doImmediateRespawn` gamerule

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/pathing/movement/CalculationContext.java
- src/main/java/baritone/process/BuilderProcess.java
add a setting to have blocks that baritone is allowed to break even with `allowBreak` set to `false`
closes #3316
> add `allowBreakAnyway` setting

- .github/workflows/gradle_build.yml
- src/main/java/baritone/command/defaults/WaypointsCommand.java
- src/main/java/baritone/utils/GuiClick.java
> Fix mistakes made while merging upwards

- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/process/BuilderProcess.java
> backport #3308 to 1.16.5

- src/api/java/baritone/api/Settings.java
I won't be able to test this before the day after tomorrow.
Fixes #3462
> Deal with others replacing the chat gui

- buildSrc/src/main/java/baritone/gradle/task/BaritoneGradleTask.java
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/api/java/baritone/api/pathing/movement/ActionCosts.java
- src/launch/java/baritone/launch/mixins/MixinClientPlayNetHandler.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/utils/BlockStateInterface.java
- src/test/java/baritone/pathing/movement/ActionCostsTest.java
Note that this does not contain changes from #3458 
Please don't merge immediately before or after updating 1.17.1 as I'd like to re-merge in that case.
Do you want updates for 1.18.1?
> Merge 1.17.1 into 1.18.2

- src/main/java/baritone/command/defaults/FindCommand.java
Sorting the positions by distance has already been done by EthanZeigler in #3249
> Find improvements

- src/api/java/baritone/api/command/helpers/Paginator.java
- src/launch/java/baritone/launch/mixins/MixinScreen.java
of course this is only discovered after I say it works and leij merges
fixes #3587
> fix click menus for baritone control

- src/main/java/baritone/command/defaults/ExecutionControlCommands.java
> Reliably clear keys when paused

- src/api/java/baritone/api/command/registry/Registry.java
It's been more than three years and we finally got the first working version of Registry.unregister!
> Fix Registry.unregister

- src/launch/java/baritone/launch/mixins/MixinScreen.java
Remove System.out.println("handleCustomClickEvent"); from MixinScreen#handleCustomClickEvent.
> Removed System.out.println.

- src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
apparently i have a error in my formula that prevents schematics with only air or exactly a power of 2 diffrent blocks from being loaded.
> formula error

- jitpack.yml
> fix jitpack.yml so 1.19 builds there again

- src/main/java/baritone/process/BuilderProcess.java
buildinlayers ~ buildonlyselection lag fix for big schematics (skips layers more properly)
uwu
> buildonlyselection optimization

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
> Allow breaking next to some liquids

- src/main/java/baritone/pathing/movement/MovementHelper.java
> Fix world border check

- src/main/java/baritone/process/BuilderProcess.java
https://github.com/cabaletta/baritone/pull/3785#pullrequestreview-1241389460
@ZacSharp
> bugfix for odd height schematics

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/pathing/movement/CalculationContext.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/pathing/movement/movements/MovementDescend.java
- src/main/java/baritone/pathing/movement/movements/MovementDiagonal.java
- src/main/java/baritone/pathing/movement/movements/MovementParkour.java
- src/main/java/baritone/pathing/movement/movements/MovementPillar.java
- src/main/java/baritone/pathing/movement/movements/MovementTraverse.java
- src/main/java/baritone/pathing/path/PathExecutor.java
Wanted to get the pr open this year :laughing:
Short term pathing is tested pretty well but for other cases I only have a random collection of manual tests.
Closes #3571
> Allow pathing to use frostwalker

- src/main/java/baritone/pathing/precompute/PrecomputedData.java
Fixes https://github.com/cabaletta/baritone/pull/3771#issuecomment-1382950808
<details><summary>Before</summary>
<details><summary>After</summary>
(Screenshots are obviously not from 1.12.2)
> Fix canWalkThrough caching

- src/main/java/baritone/process/BuilderProcess.java
rycbar wrote this
i fixed a spelling error
this seemed to work fine for me and xray
> Litematica x BuildOnlySelection support

- buildSrc/src/main/java/baritone/gradle/task/BaritoneGradleTask.java
- buildSrc/src/main/java/baritone/gradle/task/CreateDistTask.java
- buildSrc/src/main/java/baritone/gradle/task/ProguardTask.java
- fabric/build.gradle
- forge/build.gradle
- tweaker/build.gradle
> fix dist names to match previous versions

- src/main/java/baritone/command/defaults/WaypointsCommand.java
> make wp c not throw npe on invalid tag name

- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/java/baritone/gradle/task/ProguardTask.java
- src/api/java/baritone/api/utils/BlockOptionalMeta.java
> remove 1.19.3 method in blockOptionalMeta

- src/main/java/baritone/process/FarmProcess.java
> Make cocoa farmable

- src/api/java/baritone/api/pathing/goals/GoalAxis.java
- src/api/java/baritone/api/pathing/goals/GoalBlock.java
- src/api/java/baritone/api/pathing/goals/GoalComposite.java
- src/api/java/baritone/api/pathing/goals/GoalGetToBlock.java
- src/api/java/baritone/api/pathing/goals/GoalInverted.java
- src/api/java/baritone/api/pathing/goals/GoalNear.java
- src/api/java/baritone/api/pathing/goals/GoalRunAway.java
- src/api/java/baritone/api/pathing/goals/GoalStrictDirection.java
- src/api/java/baritone/api/pathing/goals/GoalTwoBlocks.java
- src/api/java/baritone/api/pathing/goals/GoalXZ.java
- src/api/java/baritone/api/pathing/goals/GoalYLevel.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/process/MineProcess.java
- src/main/java/baritone/utils/PathingControlManager.java
See #3565
From my own testing (by going through each usage of `FORCE_REVALIDATE_GOAL_AND_PATH` manually), everything should be correct
> Fix `censorCoordinates` recalc bug

- src/main/java/baritone/process/BuilderProcess.java
Let's hope I didn't miss more of that kind.
closes #3931
> Fix considering states unplaceable regardless of buildIgnoreProperties

- src/api/java/baritone/api/Settings.java
- src/api/java/baritone/api/event/events/RotationMoveEvent.java
- src/launch/java/baritone/launch/mixins/MixinEntityLivingBase.java
- src/launch/java/baritone/launch/mixins/MixinEntityPlayerSP.java
- src/launch/java/baritone/launch/mixins/MixinMinecraft.java
- src/main/java/baritone/Elytra.java
- src/main/java/baritone/behavior/LookBehavior.java
> Merge `elytra-freelook` into `elytra`

- src/main/java/baritone/utils/GuiClick.java
- src/main/java/baritone/utils/IRenderer.java
> Fix `GuiClick` not rendering the outline of the selection being made

- src/main/java/baritone/behavior/ElytraBehavior.java
> prevent <player> went off with a bang

- src/main/java/baritone/behavior/ElytraBehavior.java
- src/main/java/baritone/behavior/elytra/NetherPathfinderContext.java
> use legacy raytrace with ignore liquid to get out of lava

- src/main/java/baritone/utils/PathRenderer.java
> fix 0.5 offset in elytra path rendering

- src/api/java/baritone/api/pathing/goals/GoalAxis.java
- src/api/java/baritone/api/pathing/goals/GoalBlock.java
- src/api/java/baritone/api/pathing/goals/GoalComposite.java
- src/api/java/baritone/api/pathing/goals/GoalGetToBlock.java
- src/api/java/baritone/api/pathing/goals/GoalInverted.java
- src/api/java/baritone/api/pathing/goals/GoalNear.java
- src/api/java/baritone/api/pathing/goals/GoalRunAway.java
- src/api/java/baritone/api/pathing/goals/GoalStrictDirection.java
- src/api/java/baritone/api/pathing/goals/GoalTwoBlocks.java
- src/api/java/baritone/api/pathing/goals/GoalXZ.java
- src/api/java/baritone/api/pathing/goals/GoalYLevel.java
- src/main/java/baritone/process/BuilderProcess.java
- src/main/java/baritone/process/MineProcess.java
`hashCode` and `equals` don't like being alone.
Unless you tell me to leave out one of them I'll wait with the merge pr until this one is merged, the mask fix is merged and the rotation bug is fixed. (I have no further prs planned before the merge prs, gotta get that done).
> Implement `hashCode` for goals

- src/launch/java/baritone/launch/mixins/MixinCommandSuggestionHelper.java
It's been quite a while since I wrote this so I forgot what the difference to vanilla completion was.
I just remember that there was some detail where I decided not to mimic vanilla behavior.
In action:
https://github.com/cabaletta/baritone/assets/68165024/7acf5e73-10e0-43f1-852e-fb739929ab39
fixes #1066
> Fix tab completion with brigadier

- src/api/java/baritone/api/Settings.java
- src/api/java/baritone/api/utils/Helper.java
...and make it function. Uses that 1.19.1 tag bar system.
It could be any 24-bit colour but I just chose the same default light purple.
> Add useMessageTag setting

- src/main/java/baritone/behavior/ElytraBehavior.java
> simplify null check

- src/api/java/baritone/api/behavior/ILookBehavior.java
- src/api/java/baritone/api/behavior/look/IAimProcessor.java
- src/api/java/baritone/api/behavior/look/ITickableAimProcessor.java
- src/api/java/baritone/api/event/events/RotationMoveEvent.java
- src/launch/java/baritone/launch/mixins/MixinEntityLivingBase.java
- src/launch/java/baritone/launch/mixins/MixinEntityPlayerSP.java
- src/launch/java/baritone/launch/mixins/MixinMinecraft.java
- src/main/java/baritone/Baritone.java
- src/main/java/baritone/behavior/LookBehavior.java
- src/main/java/baritone/behavior/look/ForkableRandom.java
Fully deterministic with support for simulation of future ticks.
This PR does modify the way that RotationMoveEvent works in coordination with LookBehavior, meaning that randomLooking and simulated mouse input does have an affect on player movement. However, Baritone for 1.13+ already has affected movement because of randomLooking113.
> API for rotations produced by LookBehavior

- src/api/java/baritone/api/utils/RotationUtils.java
- src/main/java/baritone/pathing/movement/MovementHelper.java
- src/main/java/baritone/process/BuilderProcess.java
> Fix getting stuck due to impossible rotations

- build.gradle
- src/main/java/baritone/behavior/elytra/NetherPathfinderContext.java
not actually sure how much faster this is
> optimize uploading chunk data

- src/api/java/baritone/api/event/events/BlockChangeEvent.java
- src/main/java/baritone/behavior/ElytraBehavior.java
- src/main/java/baritone/behavior/elytra/NetherPathfinderContext.java
- src/main/java/baritone/event/GameEventHandler.java
> don't send the whole chunk for small changes

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/behavior/ElytraBehavior.java
- src/main/java/baritone/behavior/elytra/NetherPathfinderContext.java
> auto swap elytra

- src/main/java/baritone/behavior/ElytraBehavior.java
- src/main/java/baritone/behavior/elytra/NetherPath.java
> simple way to land at the goal

- build.gradle
- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/behavior/ElytraBehavior.java
- src/main/java/baritone/behavior/elytra/BlockStateOctreeInterface.java
- src/main/java/baritone/behavior/elytra/NetherPathfinderContext.java
> cull far away chunks from the cache

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/behavior/ElytraBehavior.java
> consistent elytra setting naming

- src/main/java/baritone/utils/GuiClick.java
- src/main/java/baritone/utils/IRenderer.java
- src/main/java/baritone/utils/PathRenderer.java
Also fixes line width settings not working since the removal of legacy OpenGL
> VulkanMod Compatibility

- build.gradle
- src/api/java/baritone/api/IBaritone.java
- src/api/java/baritone/api/behavior/IBehavior.java
- src/api/java/baritone/api/process/IElytraProcess.java
- src/main/java/baritone/Baritone.java
- src/main/java/baritone/behavior/PathingBehavior.java
- src/main/java/baritone/command/defaults/ElytraCommand.java
- src/main/java/baritone/command/defaults/ExecutionControlCommands.java
- src/main/java/baritone/command/defaults/ForceCancelCommand.java
- src/main/java/baritone/process/ElytraProcess.java
- src/main/java/baritone/process/elytra/BlockStateOctreeInterface.java
- src/main/java/baritone/process/elytra/LegacyElytraBehavior.java
- src/main/java/baritone/process/elytra/NetherPath.java
- src/main/java/baritone/process/elytra/NetherPathfinderContext.java
- src/main/java/baritone/process/elytra/NullElytraProcess.java
- src/main/java/baritone/process/elytra/PathCalculationException.java
- src/main/java/baritone/process/elytra/UnpackedSegment.java
> refactor elytra into process

- src/main/java/baritone/command/defaults/ElytraCommand.java
- src/main/java/baritone/process/ElytraProcess.java
> find safe landing spot for elytra

- src/api/java/baritone/api/process/IElytraProcess.java
- src/main/java/baritone/command/defaults/ElytraCommand.java
- src/main/java/baritone/process/CustomGoalProcess.java
- src/main/java/baritone/process/ElytraProcess.java
- src/main/java/baritone/process/elytra/NullElytraProcess.java
- src/main/java/baritone/utils/PathingControlManager.java
> make elytra play nice with CustomGoalProcess

- src/main/java/baritone/process/ElytraProcess.java
> safe landing improvements

- src/main/java/baritone/command/defaults/ElytraCommand.java
> elytra command improvements

- src/main/java/baritone/command/defaults/ElytraCommand.java
- src/main/java/baritone/process/ElytraProcess.java
> add dimension checks to elytra

- src/main/java/baritone/process/ElytraProcess.java
- src/main/java/baritone/process/elytra/BlockStateOctreeInterface.java
- src/main/java/baritone/process/elytra/ElytraBehavior.java
- src/main/java/baritone/process/elytra/NetherPathfinderContext.java
> fixes for comments in elytra pr

- src/main/java/baritone/process/ElytraProcess.java
- src/main/java/baritone/process/elytra/ElytraBehavior.java
> safer elytra landing

- src/main/java/baritone/process/ElytraProcess.java
- src/main/java/baritone/process/elytra/ElytraBehavior.java
- src/main/java/baritone/process/elytra/UnpackedSegment.java
> increase air bubble radius, append destination to path when landing

- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/behavior/LookBehavior.java
> more intuitive smooth look/free look settings

- README.md
> Add badge count badge

- build.gradle
- src/api/java/baritone/api/Settings.java
- src/main/java/baritone/process/elytra/NetherPathfinderContext.java
> add setting that makes unknown chunks air

- build.gradle
- src/main/java/baritone/process/elytra/NetherPathfinderContext.java
> make raytracer collide with unknown chunks

- src/main/java/baritone/process/elytra/ElytraBehavior.java
> recover from flying into lava (and fix ignoreLava)

- src/api/java/baritone/api/command/datatypes/BlockById.java
- src/api/java/baritone/api/command/datatypes/ItemById.java
- src/api/java/baritone/api/command/helpers/TabCompleteHelper.java
- src/api/java/baritone/api/process/IFollowProcess.java
- src/main/java/baritone/command/defaults/DefaultCommands.java
- src/main/java/baritone/command/defaults/PickupCommand.java
- src/main/java/baritone/process/FollowProcess.java
closes #1043 
closes #1439
closes #385 
also closes #3836
> Item following
